### ISSUE TITLE
falling at the first fence

### ISSUE THREAD

**Issue by gogre** [SabakiHQ/influence#1]
this is an issue with me, rather than the software - as a non-programmer, i don't understand the meaning of the responses i got and don't know what to do about them.  i was hoping it would add a View..influence feature or somesuch to Sabaki v 41 installed on my Fedora 28 machine, but this is what happened:

[d@localhost ~]$ npm install @sabaki/influence
npm WARN saveError ENOENT: no such file or directory, open '/home/d/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/d/package.json'
npm WARN d No description
npm WARN d No repository field.
npm WARN d No README data
npm WARN d No license field.

+ @sabaki/influence@1.1.4
added 1 package from 1 contributor and audited 1 package in 4.321s
found 0 vulnerabilities

**Comment by gogre** [comment]
this is an issue with me, rather than the software - as a non-programmer unused to GitHub ( i dont know whether this will appear as an edited issue or a new one!)

i also don't know what to do with:
> Then require it as follows:
> 
> const influence = require('@sabaki/influence')

am i required to edit this line into the source of Sabaki and recompile?

i don't understand the meaning of the responses i got when following the Readme instructions and don't know what to do about them -  i was hoping it would add a View..influence feature or somesuch to Sabaki v 41 installed on my Fedora 28 machine, but this is what happened instead:

[d@localhost ~]$ npm install @sabaki/influence
npm WARN saveError ENOENT: no such file or directory, open '/home/d/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/d/package.json'
npm WARN d No description
npm WARN d No repository field.
npm WARN d No README data
npm WARN d No license field.

    @sabaki/influence@1.1.4
    added 1 package from 1 contributor and audited 1 package in 4.321s
    found 0 vulnerabilities

**Comment by yishn** [comment]
This library is for users who want to include Sabaki's influence map generator in their own projects. To work with the package, you have to set up your own Node.js project first. Just look at one of the several Node.js + npm tutorials on the internet.

This module is already included in Sabaki. It's used by the score estimator which you can activate by clicking on the hamburger icon (or 'Play' menu), and then on 'Estimate'.
