### ISSUE TITLE
this SGF White in right-bottom is Dead

### ISSUE THREAD

**Issue by xiaovcn** [SabakiHQ/influence#3]
(;GM[1]AP[StoneBase:SGFParser.3.0.1]SZ[19]HA[0]KM[7.5]EV[第5届春兰杯第一轮]PB[王立诚]BR[九段]PW[宋泰坤]WR[六段]RE[白胜5又1/4子]DT[2003-12-29]PC[中国北京]SO[http://weiqi.tom.com]US[棋圣道场]C[http://weiqi.tom.com
棋圣道场-->大赛直播]
;B[pd];W[dd];B[qp];W[dq];B[oq];W[qj];B[dn];W[co];B[cf];W[ch];B[ef];W[fc];B[di];W[ce];B[bf];W[dh];B[eh];W[ci];B[dj];W[cj];B[dk];W[cl];B[dl];W[cm];B[ed];W[ec];B[cc];W[ee];B[df];W[fh];B[cd];W[eg];B[ge];W[hd];B[ei];W[dm];B[fg];W[kc];B[eq];W[ep];B[fq];W[dr];B[ql];W[qf];B[mc];W[qc];B[jc];W[jd];B[kb];W[kd];B[ib];W[ic];B[jb];W[hb];B[ie];W[id];B[qd];W[pc];B[od];W[nb];B[nc];W[mb];B[lb];W[oc];B[lc];W[rd];B[re];W[rc];B[pf];W[pg];B[og];W[of];B[nf];W[pe];B[oe];W[qe];B[ph];W[qh];B[pf];W[qg];B[kf];W[he];B[hf];W[me]C[至此中午休息，13：00继续];B[lg];W[gf];B[hg];W[jf];B[jg];W[jp];B[em];W[go];B[fo];W[fp];B[gp];W[hp];B[cn];W[bn];B[dp];W[gq];B[eo];W[cp];B[gp];W[fp];B[cq];W[do];B[ep];W[en];B[fn];W[cr];B[lq];W[hm];B[ko];W[km];B[gr];W[pq];B[op];W[jo];B[kn];W[jn];B[lm];W[kl];B[ll];W[hr];B[gp];W[hq];B[pk];W[qq];B[rp];W[pp];B[qn];W[mq];B[lr];W[mr];B[nr];W[or];B[pr];W[lp];B[kp];W[kq];B[mp];W[mo];B[lo];W[np];B[lp];W[oo];B[os];W[nq];B[ms];W[or];B[oq];W[of];B[ld];W[ng];B[pf];W[fm];B[el];W[of];B[gd];W[gc];B[pf];W[mn];B[ln];W[of];B[oh];W[le];B[pf];W[qo];B[ro];W[of];B[ke];W[mf];B[pf];W[pn];B[qm];W[of];B[je];W[hc];B[pf];W[om];B[nn];W[of];B[ob];W[pb];B[pf];W[ok];B[pj];W[of];B[oa];W[pa];B[pf];W[nm];B[mk];W[of];B[ma];W[na];B[pf];W[qr];B[sr];W[of];B[ob];W[la];B[pf];W[sq];B[rq];W[of];B[kk];W[ne];B[il];W[gn];B[fl];W[nh];B[ni];W[mi];B[nj];W[lh];B[jq];W[fr];B[er];W[gs];B[es];W[im];B[hl];W[ji];B[rj];W[ri];B[qk];W[pi];B[oi];W[qi];B[db];W[fe];B[ff];W[de];B[be];W[rk];B[rl];W[sj];B[mj];W[gm];B[dn];W[cn];B[li];W[en];B[ga];W[eb];B[dn];W[gl];B[gk];W[en];B[ea];W[ha];B[dn];W[op];B[or];W[en];B[ck];W[bk];B[dn];W[rr];B[ls];W[en];B[bq];W[br];B[dn];W[qs];B[ss];W[en];B[mh];W[dn];B[bh];W[bi];B[ah];W[mg];B[kh];W[ai];B[cg];W[dc];B[cb];W[fa];B[fb];W[gb];B[dg];W[bl];B[jr];W[fd];B[da];W[fa];B[iq];W[ip];B[gg];W[ge];B[jl];W[jm];B[sl];W[sk];B[is];W[ir];B[js];W[hs];)

[demo](http://huanle.qq.com/act/a20170110wq/index-photo.html?type=1&chess=0000000120000000000000011012022020012001112112221222221201122211211112221220122021011001121111120222112000121101200220221000122221202222221100001200222201221000000120021210112121020012222111012211010012211120021112010100111111110210222101100221221221020221100210221001211211102020221112221202121100202210002122222211112122200221000202100111200000000002210000211)

**Comment by yishn** [comment]
Is this a question or an issue? As written in the documentation:

> [The influence] map does not take dead stones into account, i.e. it will assume all stones specified in data are alive. To get better results, remove dead stones first, either manually or with the [deadstones module](https://github.com/SabakiHQ/deadstones).

**Comment by xiaovcn** [comment]
i have use the deadstones.guess(boardData, { finished: true })

**Comment by yishn** [comment]
Again, is this a question?
